#------------------------------------------------------------------------------
#
# Filename: helm-cert-manager.yaml
#
# Description: Crossplane helm provider release for cert-manager.
#
# Usage: Add as resource to kustomization.yaml for deployment.
#
# Author: James Bramich (james@nofrixion.com)
#
# History:
#   9 May      2024    James Bramich  Created, Northdown, Tasmania, Australia.
#-----------------------------------------------------------------------------
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: clusterName-cert-manager-namespace
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
  providerConfigRef:
    name: clusterName-k8s-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: cert-manager
spec:
  forProvider:
    namespace: cert-manager
    chart:
      name: cert-manager
      repository: https://charts.jetstack.io/
      version: v1.14.5
    values:
      installCRDs: true
    waitTimeout: "600s"
  providerConfigRef:
    name: clusterName-helm-provider