#------------------------------------------------------------------------------
#
# Filename: helm-external-secrets.yaml
#
# Description: Crossplane helm provider release for kubernetes external secrets operator.
#
# Usage: Add as resource to kustomization.yaml for deployment.
#
# Author: James Bramich (james@nofrixion.com)
#
# History:
#  21 May      2024    James Bramich  Created, Northdown, Tasmania, Australia.
#-----------------------------------------------------------------------------
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: clusterName-external-secrets-namespace
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: external-secrets
  providerConfigRef:
    name: clusterName-k8s-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: external-secrets
spec:
  forProvider:
    chart:
      name: external-secrets
      repository: https://charts.external-secrets.io
      version: 0.9.18
    namespace: external-secrets
  providerConfigRef:
    name: clusterName-helm-provider