#------------------------------------------------------------------------------
# Filename: ops-cluster.yaml
#
# Description: Deployment manifests for pilot ops cluster
#
# Author: James Bramich (james@nofrixion.com)
# 
# History:
# 25 March      2024  James Bramich   Created, Northdown, Tasmania
#-----------------------------------------------------------------------------
apiVersion: aws.nofrixion.com/v1alpha1
kind: Cluster
metadata:
  name: it-ops-cluster
  namespace: it-ops-cluster
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: it-ops-1
    region: eu-west-1
    version: "1.28"
    iam:
      # replace with your custom arn like:
      # roleArn: arn:aws:iam::123456789:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
      # roleArn: ${data.aws_eks_iam_default_admin}
      roleArn: arn:aws:iam::145259453615:role/AWSReservedSSO_AdministratorAccess_d3980a6c9782fd6d
    # EntraID integration
    identityProvider:
      clientId: f2653318-e686-4fd1-85ec-5cf692ba0b20
      issuerUrl: https://sts.windows.net/97c78528-728a-4eb7-b50e-ee7aced0a1ce/
      adminGroupId: efaddfcc-7846-48db-a87b-62a211452c74 # NoFrixion-SysAdmins
    nodes:
      count: 3
      instanceType: t3.small
  writeConnectionSecretToRef:
    name: it-ops-cluster-aws-kubeconfig