#------------------------------------------------------------------------------
# Filename: definition.yaml
#
# Description: Composite resrouce definition for EKS compliant VPC. Based on:
#                  https://github.com/upbound/configuration-aws-network/blob/main/apis/definition.yaml
#
# Author: James Bramich (james@nofrixion.com)
#
# History:
# 25 March      2024  James Bramich   Created, Northdown, Tasmania
#-----------------------------------------------------------------------------

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.aws.platform.nofrixion.com
spec:
  connectionSecretKeys:
    - kubeconfig
  group: aws.platform.nofrixion.com
  names:
    kind: XNetwork
    plural: xnetworks
  claimNames:
    kind: Network
    plural: networks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: Network Parameters
                  properties:
                    id:
                      type: string
                      description: ID of this Network that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                  required:
                    - deletionPolicy
                    - providerConfigName
                    - id
                    - region
                  type: object
              required:
                - parameters
            status:
              type: object
              properties:
                vpcId:
                  type: string
                subnetIds:
                  type: array
                  items:
                    type: string
                publicSubnetIds:
                  type: array
                  items:
                    type: string
                privateSubnetIds:
                  type: array
                  items:
                    type: string
                securityGroupIds:
                  type: array
                  items:
                    type: string