apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeclusters.devopstoolkitseries.com
  labels:
    idp: "true"
spec:
  connectionSecretKeys:
  - kubeconfig
  - value
  defaultCompositionRef:
    name: cluster-aws
  group: devopstoolkitseries.com
  names:
    kind: CompositeCluster
    plural: compositeclusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Cluster that other objects can refer.
              parameters:
                type: object
                description: Parameters used to customize the cluster
                properties:
                  version:
                    description: The Kubernetes version for the cluster.
                    type: string
                  nodeSize:
                    description: The size of the nodes; small, medium, large.
                    type: string
                  minNodeCount:
                    description: The minimum number of nodes.
                    type: integer
                    default: 1
                  namespaces:
                    description: List of Namespaces that should be created in the cluster
                    type: array
                    items:
                      type: string
                    default:
                      - dev
                      - production
                  apps:
                    type: object
                    description: List of apps that should be installed in the cluster
                    properties:
                      crossplane:
                        type: object
                        description: Install Crossplane
                        properties:
                          enabled:
                            type: boolean
                            default: false
                      openfunction:
                        type: object
                        description: Install OpenFunction
                        properties:
                          enabled:
                            type: boolean
                            default: false
                      dapr:
                        type: object
                        description: Install Dapr. Do not enable it if OpenFunction is enabled since it comes with Dapr.
                        properties:
                          enabled:
                            type: boolean
                            default: false
                      traefik:
                        type: object
                        description: Install Traefik.
                        properties:
                          enabled:
                            type: boolean
                            default: false
                      dynatrace:
                        type: object
                        description: Install Dynatrace operator. A secret `dynatrace` with tokens musts exist in the `dynatrace` Namespace.
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          apiUrl:
                            type: string
                            description: The URL of the Dynatrace API
                          oathCredentialsSecretName:
                            description: The name of the secret with the OAuth credentials for the Dynatrace API.
                            type: string
                      externalSecrets:
                        type: object
                        description: Install External Secrets Operator (ESO)
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          store:
                            type: boolean
                            description: Whether to create secret store. If `true`, `creds` field needs to be set as well.
                          googleCredentialsKey:
                            type: string
                            description: The key with Google credentials in the secret. Works only with clusters in Google Cloud.
                          awsAccessKeyIDKey:
                            type: string
                            default: accessKeyID
                            description: The key with Access Key ID in the secret. Works only with clusters in AWS.
                          awsSecretAccessKeyKey:
                            type: string
                            default: secretAccessKey
                            description: The key with Secret Access Key in the secret. Works only with clusters in AWS.
                          azureVaultUrl:
                            type: string
                            description: The URL of Azure Vault. Works only with clusters in Azure.
                          secrets:
                            type: array
                            description: List of secrets to be created from the secret store. The `store` parameter must be set to `true` for this feature to work.
                            items:
                              type: object
                              properties:
                                fromSecret:
                                  type: string
                                  description: The name or the key of secret in the external secret store
                                toSecret:
                                  type: string
                                  description: The name of the secret
                                toNamespace:
                                  type: string
                                  description: The namespace of the secret
                                type:
                                  type: string
                                  description: The type of the secret
                                  default: Opaque
                              required:
                              - fromSecret
                              - toSecret
                              - toNamespace
                  creds:
                    type: object
                    description: The secret with hyperscaler credentials.
                    properties:
                      name:
                        type: string
                        description: The name of the secret
                      namespace:
                        type: string
                        description: The namespace of the secret
                        default: crossplane-system
                      keys:
                        description: The keys in the secret
                        type: array
                        items:
                          type: string
                    required:
                    - name
                    - namespace
                    - keys
                required:
                - nodeSize
            required:
              - id
              - parameters
          status:
            type: object
            properties:
              clusterName:
                description: The name of the cluster.
                type: string
              controlPlaneStatus:
                description: The status of the control plane.
                type: string
              nodePoolStatus:
                description: The status of the node pool.
                type: string
              field1:
                description: A placeholder
                type: string
    additionalPrinterColumns:
    - name: clusterName
      type: string
      jsonPath: ".status.clusterName"
    - name: controlPlane
      type: string
      jsonPath: ".status.controlPlaneStatus"
    - name: nodePool
      type: string
      jsonPath: ".status.nodePoolStatus"