#------------------------------------------------------------------------------
# Filename: definition.yaml
#
# Description: Composite resrouce definition for EKS cluster. Based on:
#                  https://github.com/upbound/configuration-aws-eks/blob/main/apis/definition.yaml
#
# Author: James Bramich (james@nofrixion.com)
#
# TODO
# - add additional parameters for additional core services/operators(see ./composition.yaml for details)
#
# History:
# 25 March      2024  James Bramich   Created, Northdown, Tasmania
#-----------------------------------------------------------------------------
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.aws.nofrixion.com
spec:
  connectionSecretKeys:
    - kubeconfig
  group: aws.nofrixion.com
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: EKS configuration parameters.
                  properties:
                    id:
                      type: string
                      description: ID of this Cluster that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    tags:
                      type: object
                      description: Tags to be applied to ALL resources created in this composite resource.
                      additionalProperties:
                        type: string
                    iam:
                      type: object
                      description: IAM configuration to connect as ClusterAdmin.
                      properties:
                        roleArn:
                          description: The IAM Role ARN to connect as ClusterAdmin.
                          type: string
                          default: roleArn
                        userArn:
                          description: The IAM User ARN to connect as ClusterAdmin.
                          type: string
                          default: userArn
                        autoscalerArn:
                          description: The AutoScaler Role ARN to connect as ClusterAdmin.
                          type: string
                          default: autoscalerArn
                    identityProvider:
                      type: object
                      description: Configuration for adding EntraID as an OIDC identity provider with the cluster.
                      properties:
                        clientId:
                          description: Client ID of enterprise application set up for OIDC provider in EntraID
                          type: string
                        issuerUrl:
                          description: Issuer URL of enterprise application set up for OIDC provider in EntraID
                          type: string
                        groupsClaim:
                          type: string
                          default: groups
                        usernameClaim:
                          type: string
                          default: upn
                        adminGroupId:
                          description: Azure EntraID group object ID for group to add to 'cluster-admin' 
                          type: string
                      required:
                        - clientId
                        - issuerUrl
                        - adminGroupId
                    vpcConfig:
                      type: object
                      properties:
                        publicAccessCidrs:
                          description: Indicates which CIDR blocks can access the Amazon EKS public API server endpoint. 
                          type: array
                          items:
                            type: string
                          default: ['0.0.0.0/0']
                    existingOidcProvider:
                      type: string
                      description: crossplane.io/external-name of an existing OIDC provider resource.
                    existingNetwork:
                      type: object
                      description: Only required if crossplane is to assume management of an existing VPC
                      properties:
                        vpcId:
                          type: string
                        publicSubnetIds:
                          type: array
                          items:
                            type: string
                        privateSubnetIds:
                          type: array
                          items:
                            type: string
                        internetGatewayId:
                          type: string
                        natGatewayId:
                          type: string
                        eipAllocationId:
                          type: string
                        privateRouteTableId:
                          type: string
                        privateRouteId:
                          type: string
                        publicRouteTableId:
                          type: string
                        publicRouteId:
                          type: string
                        mainRouteTableAssociationId:
                          type: string
                        publicRouteTableAssociationIds:
                          type: array
                          description: Public route table associations in order from zone a->c
                          items:
                            type: string
                        privateRouteTableAssociationIds:
                          type: array
                          description: Private route table associations in order from zone a->c
                          items:
                            type: string
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    version:
                      description: Kubernetes version
                      type: string
                      enum:
                        - "1.29"
                        - "1.28"
                        - "1.27"
                        - "1.26"
                        - "1.25"
                      default: "1.28"
                    nodes:
                      type: object
                      description: EKS node configuration parameters.
                      properties:
                        count:
                          type: integer
                          description: Desired node count, from 1 to 100.
                        instanceType:
                          type: string
                          description: instance types associated with the Node Group.
                          default: t3.small
                      required:
                        - count
                        - instanceType
                  required:
                    - id
                    - identityProvider
                    - region
                    - deletionPolicy
                    - providerConfigName
                    - nodes
              required:
                - parameters
            status:
              description: A Status represents the observed state
              properties:
                eks:
                  description: Freeform field containing status information for eks
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                subnetIds:
                  type: array
                  items:
                    type: string
              type: object